parallelize regression tests

diff --git a/test_one b/test_one
--- a/test_one
+++ b/test_one
@@ -43,30 +43,48 @@ true)
   ;;
 esac
 
-for input_cl in "$@"; do
-  echo
-  yellow "$input_cl"
+do_test() {
+  input_cl=$1
   if [[ ! -f "$input_cl" ]]; then
-    red "FILE NOT FOUND"
-    continue
+    red "FILE NOT FOUND $input_cl"
+    return
   fi
 
   if [[ "$input_cl" == *"bad"* ]]; then
     if diff -u --color \
       --label actual <(actual "$input_cl" | grep --invert-match "|" | sort_by_lineno) \
       --label expected <(expected "$input_cl" | sort_by_lineno); then
-      green PASS
+      echo 1 >>passed
     else
       red FAIL
+      echo "$input_cl" >>failed_input
     fi
   else
     # does not sort to preserve valid AST in diff'ing
     if diff -u --color \
       --label actual <(actual "$input_cl" | grep --invert-match "|") \
       --label expected <(expected "$input_cl"); then
-      green PASS
+      echo 1 >>passed
     else
       red FAIL
+      echo "$input_cl" >>failed_input
     fi
   fi
+}
+
+trap "rm -r passed total failed_input" EXIT
+for input_cl in "$@"; do
+  echo 1 >>total
+  ((i = i % 8))
+  ((i++ == 0)) && wait
+  do_test "$input_cl" &
 done
+wait
+
+echo
+t=$(wc total -l)
+p=$(wc passed -l)
+yellow "SUMMARY: $p / $t"
+red "FAILED FILES"
+red "$(uniq failed_input)"
+echo
